### ISSUE TITLE
Feature: Restricting the list of allowable domains

### ISSUE THREAD

**Issue by coooolers** [o15y/staart#114]
Email domain: Enter your company's domain, eg. oswaldlabs.com
We'll allow people with emails from this domain to join this organization automatically

Do not allow the public domains to be included in this list like gmail, hotmail, rediffmail, and many others.

**Comment by coooolers** [comment]
A super-admin could be probably allowed to maintain the names of the restricted domains.

**Comment by AnandChowdhary** [comment]
Good plan! There are quite a few nice NPM packages for this, I'll make sure to add that validation. The feature of email restriction actually doesn't work, it's currently just a setting you can save, but I plan on shipping that this week too.

We already have a helper function for detecting educational emails using my package [Edumail](https://github.com/AnandChowdhary/edumail), and something similar can be used to prevent free/temporary/disposable email addresses too.

**Comment by AnandChowdhary** [comment]
I've added a Staart-wide check for disposable emails while signing up or inviting a member. You can use the environment variable `ALLOW_DISPOSABLE_EMAILS` to control the setting. By default, disposable emails are not allowed.

For teams and company domain emails, I will make sure also not allow public email providers like Gmail, that's in the works! 😄

**Comment by coooolers** [comment]
Great!

I'd like to request to create a super-admin role that controls the list of restrictive domains like gmail, etc.

**Comment by AnandChowdhary** [comment]
Staart now has support for whitelisted domains:

![Screen Shot 2019-07-22 at 14 36 11](https://user-images.githubusercontent.com/2841780/61620803-34f0ae00-ac8f-11e9-9ee9-26cd2aa8919a.png)

You can add any number of domains to your team, and verify them by uploading a file or adding a DNS `TXT` record:

![Screen Shot 2019-07-22 at 14 45 23](https://user-images.githubusercontent.com/2841780/61620887-623d5c00-ac8f-11e9-8adf-568d8360c872.png)

Then, you can choose to:

1. Only allow managers to invite members from approved domains, and
2. Automatically let users with an email on that domain to join your team
