### ISSUE TITLE
Feature: Check input against regular expression

### ISSUE THREAD

**Issue by coooolers** [o15y/staart#115]
Regular expressions could be for Name (only alpha letters), Password (strong password with special characters, minimum length), Domain name (occurrence of dot) etc.

Better if we display the Password Strength meter.

**Comment by AnandChowdhary** [comment]
Do you mean this for the frontend? If yes, maybe it's a better idea to open this issue in the Staart UI repository, since this is primarily the backend and build tools.

**Comment by AnandChowdhary** [comment]
We currently do validate using the internal `validator` helpers. The rule (I think) is name should be a string of at least 3 characters, and password/domain should be strings. I didn't want to be too strict with the password rules, but it's something I will look into. Thanks again for opening these issues!

**Comment by coooolers** [comment]
@AnandChowdhary Thx. for the detailed replies. 

Yes, the validations should be applied at both the ends i.e. UI and backend. So probably, you may create a common/validators folder and share the code.

**Comment by AnandChowdhary** [comment]
@all-contributors can you please add @coooolers for bugs and ideas? Thanks!

**Comment by AnandChowdhary** [comment]
@all-contributors can you please add @coooolers for bugs and ideas?

**Comment by AnandChowdhary** [comment]
@all-contributors can you please add @coooolers for bugs and ideas?

**Comment by AnandChowdhary** [comment]
I've added better validation for names (alphabet and space), passwords (minimum length), and domains (regex).
