### ISSUE TITLE
Remove CORS * in favor of allowed domains

### ISSUE THREAD

**Issue by AnandChowdhary** [o15y/staart#134]
Instead of sending in a CORS *, allow API keys to have a list of allowed referrers, and only allow those in Access-Control-Allow-Origin

**Comment by kiwicopple** [comment]
How do you guys run this locally with Staart UI now that you have removed this? I am testing this out with docker-compos. I have `staart` on port `7007` and the `ui` on `3000` so I am getting CORs errors when the `ui` tries to call the API

**Comment by AnandChowdhary** [comment]
Hi @kiwicopple, good question! In production, you should use an API key when using Staart UI. But, it doesn't make sense for development, so I've added CORS `*` back in 3a63a30.

You can now use the environment variable `DISALLOW_OPEN_CORS` to not add the CORS header without an API key, which should be the convention for production.

**Comment by kiwicopple** [comment]
That's great @AnandChowdhary thanks for the fast response. I really like the concept of staart. I'm having a bit of trouble getting the UI working with it out of the box but perhaps I'll open an issue over on the other repo if I can't solve it.
