### ISSUE TITLE
Is V4 stable? 

### ISSUE THREAD

**Issue by zzmao** [o15y/staart#1790]
Hello, 

I see a warning from readme:

```v3 BETA WARNING: The master branch and all 3.x releases are currently in beta. For production, use v1.x instead.```

but looks like the project has upgraded to v4. 

Just want to double check if the warning still valid? and is V4 stable? 

Thanks,
Z

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
