### ISSUE TITLE
Swagger - Add bearer token to make it usable

### ISSUE THREAD

**Issue by shadowmodder** [o15y/staart#1791]
<deleted>

**Comment by shadowmodder** [comment]
if you could add bearer token or apikey to the swagger document builder it would be helpful: 

    .addBearerAuth(
      { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },'access-token',
    )


Please let me know if I can open a branch and push these or any new proposed changes, I would love to help.

**Comment by AnandChowdhary** [comment]
Absolutely, happy to accept a PR!

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
