### ISSUE TITLE
    Fix swagger /v bug in curl posts

### ISSUE THREAD

**Issue by shadowmodder** [o15y/staart#1792]
Fix swagger /v bug in curl posts
    
    currently, all curl requests from swagger are missing /v1 in the URL
    this fix will ensure swagger knows about the app context to V1
    
    moving the swagger below app.setGlobalPrefix('v1') will provide the /v1
    context into swagger CURL requests

**Comment by AnandChowdhary** [comment]
Let's do it, happy to accept a PR!

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
