### ISSUE TITLE
Update docs to include getting started guide

### ISSUE THREAD

**Issue by solarpanda** [o15y/staart#180]
Would be great if you could add a getting started guide for developing on staart ui with the staart backend wired up, maybe docker?

**Comment by AnandChowdhary** [comment]
Good suggestion! This is definitely a very important todo. I'm adding the last few features (for example, I shipped session invalidation last week) and as soon as I'm confident we're mostly done, I'll spend time on comprehensive documentation, perhaps add Swagger too.

**Comment by AnandChowdhary** [comment]
We have a fairly decent getting started guide now, along with some other articles: https://staart.js.org/backend.

Also interesting to note is [Staart Site](https://github.com/staart/site), the starter for static sites our docs website uses.
