### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by dnrun** [o15y/staart#1805]
Was really looking forward to checking this out but unfortunately the "config.ts" doesn't exist. When I build the docker container it errors out

```
> @staart/api@4.0.9 start:prod /usr/src/app
> node dist/src/main

internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 
Error: Error loading shared library /usr/src/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node: Exec format error
```

Can someone please update the documentation please?

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
