### ISSUE TITLE
OAuth Feature

### ISSUE THREAD

**Issue by jordanparker6** [o15y/staart#2004]
Does this boilerplate provide means of authenticating via OAuth (e.g. Google / Github)?

**Comment by AnandChowdhary** [comment]
Unfortunately not, but it's definitely something I want to work on :)

**Comment by jordanparker6** [comment]
@AnandChowdhary awesome! I plan using this repo but removing basic and totp auth and replacing it with OAuth2 / OpenID with passport.js. I am don't plan on managing passwords. I will leave that to the identity providers. Happy to share code back for you to figure out how you would like to integrate it into the existing repo.

I can also share back some unit tests where the original code hasn't substantial deviated.

**Comment by AnandChowdhary** [comment]
Sounds amazing, thanks a ton!

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
