### ISSUE TITLE
I have this error Typejoi_1.default.validate

### ISSUE THREAD

**Issue by yagobski** [o15y/staart#372]
I have this error after fresh install

Backup error Typejoi_1.default.validate is not a function

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue! I found this a few days ago and was hoping to fix it over the weekend. The dependency update of Joi has a changed API.

In the meantime, you can downgrade Joi and @types/Joi to the last major version and everything should work. :)

**Comment by AnandChowdhary** [comment]
I've reverted Joi to the most recent stable version with `@types` support.
